### ISSUE TITLE
Look in to automating adding users to the calendar event for their CoP

### ISSUE THREAD

**Issue by chelseybeck** [hackforla/tables#16]
### Overview
We need to automate adding users to specific Community of Practice Google Calendar events.

### Action Items
- [x] Add Tables account to all Community of Practice Calendars as an owner.
- [x] Put Calendar IDs into Tables.
- [x] Put all Community of Practice event hashes into Tables.
- [x] Create a function that adds users to the Communities of Practice's calendar invites in App Scripts.

**Comment by averdin2** [comment]
Update: 
I tried to just use the Tables calendar as a way to add users to the various events. I am not sure why, but I cannot add users to the calendar event this way. Tables needs to have owner access to all the Communities of Practice's calendars. From here I can create the script to add users to the calendar invites.

**Comment by averdin2** [comment]
As of 1/20/2022, the current version of the project is able to add users to all Community of Practice calendar invites. However, it does not notify people that they have been added to the calendar invite. There is also a problem with people that do not use a proper gmail account for their invites. It does not seem able to send invites to other mail accounts.

I am going to close this issue as this functionality is working. If it is needed later to update this functionality, a new issue can be created.
