### ISSUE TITLE
Roster Reports

### ISSUE THREAD

**Issue by averdin2** [hackforla/tables#17]
### Overview
We need to create google sheets with our automation to act as rosters for the different communities of practice. This is a part of our MVP that we are looking to deliver by November 28th.

### Action Items
- [x] Update community of practice tables columns (schema) (see: https://github.com/hackforla/CivicTechJobs/issues/13)
- [x] Update user schema to match https://github.com/hackforla/tables/issues/17#issuecomment-974995536
- [ ] Create new google sheets using app scripts for each community of practice
- [ ] Populate Tables with current Rosters (Meet with Bonnie and do this)
- [ ] Standardize roster schemas across all Communities of Practice (discussion phase)
- [ ] Set up a time schedule for updating google sheets with Tables and App Scripts (Every night)
- [ ] Delete old sheets and create updated roster sheets when roster is updated

### Resources/Instructions
For using Google Sheets with App Scripts:
Video tutorial for Sheets: 
https://www.youtube.com/playlist?list=PL42xwJRIG3xBZFP5wYh-OFb-CQmjz-Rn-

Article Resources:
https://developers.google.com/apps-script/reference/spreadsheet/spreadsheet-app
https://stackoverflow.com/questions/48617251/how-to-update-row-data-of-google-spreadsheet-using-google-app-script
https://stackoverflow.com/questions/46575644/could-i-use-one-google-script-to-multiple-spreadsheets
https://developers.google.com/apps-script/guides/standalone

**Comment by averdin2** [comment]
We need to see the difference between Google's Spreadsheets and Sheets API. Play around with a dummy sheet and the API to see what values are returned.

**Comment by ExperimentsInHonesty** [comment]
User table for the form as of 2021-11-21
nameFirst: String
nameLast: String
gmail: String (email validation)
preferedEmail:
createdDate: (auto)
UserStatus: (see User Status Table) (Automatically add them as active)
~practiceAreaCurrent: (see Practice Area Table)~
jobTitleCurrent: user’s current professional/non-HfLA job
practiceAreaTarget: (see Practice Area Table) - can choose multiple
jobTitleTarget: String

~DesiredRoles user’s desired contributor roles at HfLA (structured and comes from the CivicTechJobs data) - Talk to Ava about it.~

~CurrentSkills user’s current skills they want to use as a volunteer~
~TargetSkills user’s target skills to acquire as a volunteer~
LinkedinAccount user’s public linkedin profile URL
referredBy: (see Referrer Table)
firstAttended: Date (Automatically add the date filled out)
githubHandle: (make sure it does not include https://github.com/)
phone:
textingOk: Boolean
slackID: Number (specific number of chars)
isHflaGithubMember: Boolean (update this automatically when they have been added to github
github2FA: Boolean (this should be in db but we will have to write a script to check for it)
githubMembershipPublic: Boolean (this should be in db but we will have to write a script to check for it)
~availability: (see Brigade/GMT Time Bucket Table) This is translated into GMT on the way in. (see #13 (comment))~
TimeZone: TimeZoneObj
Conduct: Boolean
~GoogleOrgCheck: DateObj~
~SlackOrgCheck: DateObj~
~GitHubOrgCheck: DateObj~
Last Modified: DateObj
~Password: Hashed String~

**Comment by averdin2** [comment]
Our User Schema:
First Name, Last Name, Status, CoP Name, Project Name, Current Role, Desired Role, eMail, Phone Number, Texting (boolean), Slack Name, Slack ID, GitHub, LinkedIn, Time Zone, Availability, Last Updated, Last updated by

**Comment by averdin2** [comment]
Need to test what the Gmail field will return to the App Script. It might not be a string initially. Integrate this with the current functions for adding people to Google Drives

**Comment by averdin2** [comment]
We were able to update the rosters using Tables and Google sheets formula functions.
