### ISSUE TITLE
Update Roster Research

### ISSUE THREAD

**Issue by averdin2** [hackforla/tables#19]
### Overview
We need to decide on how we will implement updating rosters. We were thinking of two ways. One way was to delete the file and create a new file on update. Another way was to just update the file. This is a sub-issue of issue #17. 

### Action Items
- [ ] Research how to use App Scripts to get the file into a specific folder
- [ ] Find the best way to update the roster and put the file into that specific folder

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by chelseybeck** [comment]
I think that we should create the sheets in a Tables drive and then just create blank sheets in each of the community of practice drives and use the importdata() function inside of those sheets to bring in data from the sheets in the Tables drive.

**Comment by averdin2** [comment]
Thinking about implementing volunteer ID for look-up.

**Comment by averdin2** [comment]
We were able to update the roster using Google Sheet formulas.
