### ISSUE TITLE
Sync onboarding prototype with a folder in the website repository

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/tables#2]
### Dependency 
hackforla/tables#1 

### Overview
As a developer, going into the Google Apps Script interface to edit the code is not only a hassle, but an opaque process. Since it acts as our "backend", the script should exist in our repo and synced instead.

### Action Items

- [ ] Create a piece of code, workflow, or otherwise, that allows code that lives in a specific place in our repo to be reproduced in another specific place in our Google Suite.
  - [ ] The place in our Google Suite should be where our Onboarding Apps Script is stored and run.
  - [ ] Changes in the specific file in our repo should should reflect in the place in our Google Suite
  - [ ] Changes in the place in our Google Suite **should not** reflect in our repo. In other words, the changes are one way only! But do feel free to add a comment on the script noting that if it is viewed on Apps Script, changes will be erased.

### Resources/Instructions
Something to consider: Because the website project is hosted on GitHub Pages, as of this comment, **it is impossible to protect API keys**. Therefore, whatever way you implement the syncing of the two scripts, if an API call is used, you must also consider the long term security of the key. This project is very free-form, and requires a lot of decision points, so do consult with others in the process of working on this!

**Comment by averdin2** [comment]
We are closing this issue because we do not want this code to be on GitHub.
