### ISSUE TITLE
Roster Data Import CoP

### ISSUE THREAD

**Issue by averdin2** [hackforla/tables#20]
### Overview
We need to import Roster Data into Google Tables

### Action Items
- [ ] Create a duplicate sheet of the roster.
- [ ] Update roster field names to match Tables field names (may need to add or remove some fields). You may use [this sheet](https://docs.google.com/spreadsheets/d/1MsWfdTHISiIjxd3ba4Go2vM5_eAD56mswanTmzdTgr0/edit?usp=sharing) for cleaning. If it's in use, make a copy.
- [ ] Split name field into first & last. [Here](https://support.google.com/docs/answer/3094136?hl=en) is a link explaining the SPLIT function. You'll have to create four new columns for this task - to the right of the existing name column, split the name column into the next two columns, and then copy each column into an empty column pasting values only. 
- [ ] Once data in sheet (roster) completely aligns with the data in the table, copy the data in the sheet (starting with the name_first column) and paste it into the table (starting with the name_first). 

### Resources/Instructions
REPLACE THIS TEXT -If there is a website that has documentation that helps with this issue provide the link(s) here.

- [x] Data Science
- [x] Dev Ops
- [x] Engineering
- [x] Revenue
- [x] UI/UX
- [x] Marketing
- [x] Product Management

**Comment by averdin2** [comment]
@chelseybeck : Data Science, Dev Ops, and Engineering.
@jpandh : Revenue and UI/UX
@averdin2 : Marketing and Product Management

**Comment by chelseybeck** [comment]
@averdin2 @jpandh - I've updated the table to include the DevOps, Data Science, and Engineering CoPs. Will message in Slack to see if you want me to do the rest as well.

**Comment by averdin2** [comment]
We were able to import all the Community of Practice rosters from their google drives.
