### ISSUE TITLE
Create mock repo and team for tables automation testing

### ISSUE THREAD

**Issue by chelseybeck** [hackforla/tables#3]
### Overview
The tables team needs write permission to every CoP and project drive as well as the GitHub org.

### Action Items

- [ ] Add tables@hackforla.org as editor to all CoP & project drives.
- [ ] Add @hflatables to the org with write permissions.

[Original Issue](https://github.com/hackforla/website/issues/1833#issue-929785416)

**Comment by averdin2** [comment]
We are currently implementing the first demo. This will be put in the ice box until first demo is complete.
