### ISSUE TITLE
Google Drive: Add User: Change default permission level

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tables#36]
### Overview
We need to change the default level to give to new people to be `Contributor` instead of `Content Manager` so that people can't delete files.

### Action Items
- [x] Review this issue https://github.com/hackforla/tables/issues/27
- [x] Figure out how to lower the permissions for all new users added
- [x] Test with new users
- [x] validate that new users are receiving appropriate permission
- [x] Send to product to create an issue to let all the PMs know that they have to downgrade the permissions for all current members to `contributor`

### Resources/Instructions
https://github.com/hackforla/tables/wiki/Resources

**Comment by hang-justin** [comment]
In the google scripts that is run when a row is added, the properties are set as follow in the addUserToDrive helper func:
 
```
  let properties = {
    role: 'writer',
    value: gmail,
    type: 'user'
  };
```

These settings should be equivalent to the `Contributor`

https://developers.google.com/drive/api/guides/ref-roles

**Comment by hang-justin** [comment]
- [ ] test

<font size=24>

- [ ] test2

**Comment by hang-justin** [comment]
- Discovered that the script was hitting a timeout issue
- Script has 30s to run
- Timeout issue was due to adding a user to calendar
- Adding a single CoP's calendar to the user could take from 10 - 20s

Google function runtime limit
- 30sec/execution
- Function call can only run for 30sec max before timing out and exiting
- https://developers.google.com/apps-script/guides/services/quotas


~~Google Drive API Rate limits:~~
- 3/sec
- 20k/100sec
- https://developers.google.com/drive/api/guides/limits

**Comment by hang-justin** [comment]
Limitations:

- 5,000 bot actions per table (per month)
- A bot can fire at most 100 times per hour (https://support.google.com/area120-tables/answer/10011560)
- A script/function runtime can run at most 30 sec / execution before timing out (https://developers.google.com/apps-script/guides/services/quotas)

**Comment by hang-justin** [comment]
Product Management and Marketing team has a lot of content managers.

How to proceed for the last task,` Send to product to create an issue to let all the PMs know that they have to downgrade the permissions for all current members to contributor`?

**Comment by ExperimentsInHonesty** [comment]
- A new issue has been created to audit the current drives to see what permissions need to be downgraded #51
