### ISSUE TITLE
Make test table email

### ISSUE THREAD

**Issue by hkatzdev** [hackforla/tables#46]
### Overview
Make a test email to ensure the main account isn't affected from testing

### Action Items
- [ ] Make a new email
- [ ] Switch testing table and appscript over to new email
- [ ] Update testing secret

**Comment by aishwaryaharikumar** [comment]
product is happy to make the email, what should we call it?

**Comment by hkatzdev** [comment]
tables-staging@hackforla.org is an acceptable email.

**Comment by ExperimentsInHonesty** [comment]
The email address has been added.
