### ISSUE TITLE
Add new website team members to google drive

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tables#47]
### Overview
We need to add new website team members to the website teams google drive during onboard, and via form filling out in break out room, so that the website team lead does not have to do it manually

### Action Items
- [x] Add tables@ to the website team google drive
- [x] Review the current script for adding cop members to cop drives
- [x] Make new a new script that will work for a team drive.  
   - The test is the website team
   - person should get added as a contributor
- [x] update wiki with details

### Resources/Instructions
- email / github user that does the inviting hfla-website-checklist@hackforla.org
- [form](https://tables.area120.google.com/u/0/form/80QWxNLn_ehajAGpCcx4Ej/t/9zbNZkfHUltaJ3isu4c4ywbrD_O8ucFn5cUruf1Mf_at8ZmOdy7ADrF1xnRNF6p4O0) that website team lead will use
- [table ](https://tables.area120.google.com/u/0/workspace/bHKoRlcCZyubeRsnie2OgH/table/8UiKk90_KmN7QJAp8UX_1R)with website team data - populated by the form.
- [website team drive](https://drive.google.com/drive/folders/0AKWbU6_2dvZuUk9PVA)
-

**Comment by ExperimentsInHonesty** [comment]
@hang-justin Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by hang-justin** [comment]
Script works and adds user to google drive as a contributor

[website-onboarding-form.md](https://github.com/hackforla/tables/blob/main/dev-docs/website-onboarding-form.md)
