### ISSUE TITLE
Add new website team members to website team table via form

### ISSUE THREAD

**Issue by aishwaryaharikumar** [hackforla/tables#48]
### Overview
We need to add new website team members to the website teams table via form during onboard, and via form filling out in break out room, so that the website team lead does not have to do it manually

### Action Items
- [x] Identify requirements for form
- [x] Review the main onboarding form for adding people to tables
- [x] Make new a new form that will work for website team table
- [x] Add form example to the wiki

### Resources/Instructions
- [form](https://tables.area120.google.com/u/0/form/80QWxNLn_ehajAGpCcx4Ej/t/9zbNZkfHUltaJ3isu4c4ywbrD_O8ucFn5cUruf1Mf_at8ZmOdy7ADrF1xnRNF6p4O0) that website team lead will use
- [table ](https://tables.area120.google.com/u/0/workspace/bHKoRlcCZyubeRsnie2OgH/table/8UiKk90_KmN7QJAp8UX_1R)with website team data - populated by the form.

**Comment by aishwaryaharikumar** [comment]
Requirements for form - 
- First Name
- Last Name
- Email
   - Invites are sent through google calendar invites. A gmail is suggested, but not required.
- GitHub Handle
   - Please provide your GitHub Handle (NOT your GitHub profile URL).
   - Your GitHub Handle appears underneath your name on your GitHub profile (i.e. ExperimentsInHonesty)
- Attend Website Team Meeting (all roles)?
   - Sunday, 10AM - 12PM Pacific Time (YES/NO)
- Attend Website Dev Team Meeting?
   - Tuesday, 7PM - 8PM Pacific Time (YES/NO)
- Attend Dev Office Hours?
   - Thursday, 7PM - 8PM Pacific Time (YES/NO)

**Comment by hang-justin** [comment]
Documentation on form added
