### ISSUE TITLE
Add new table for website team

### ISSUE THREAD

**Issue by aishwaryaharikumar** [hackforla/tables#49]
### Overview
We need to add new table for website team members to be able to automate all of the onboarding actions 

### Action Items
- [x] Define which tables are needed
- [x] Create schema for table
- [x] cleanup schema (see notes below)
- [x] add relevant info to wiki, so that we have a documented model for team on tables.

### Resources/Instructions
- email / github user that does the inviting hfla-website-checklist@hackforla.org
- [form](https://tables.area120.google.com/u/0/form/80QWxNLn_ehajAGpCcx4Ej/t/9zbNZkfHUltaJ3isu4c4ywbrD_O8ucFn5cUruf1Mf_at8ZmOdy7ADrF1xnRNF6p4O0) that website team lead will use
- [table (Website Team Onboarding)](https://tables.area120.google.com/u/0/workspace/bHKoRlcCZyubeRsnie2OgH/table/8UiKk90_KmN7QJAp8UX_1R) with website team data - populated by the form.
- [table (Weekly Website/Dev Meetings)](https://tables.area120.google.com/u/0/workspace/bHKoRlcCZyubeRsnie2OgH/table/8lS3wt0ttgX4WDb-KSCOlz)
- [website team drive](https://drive.google.com/drive/folders/0AKWbU6_2dvZuUk9PVA)
-

**Comment by aishwaryaharikumar** [comment]
Tables needed
- Weekly Website/Dev Meetings
- Website Team Onboarding

**Comment by aishwaryaharikumar** [comment]
Tables Schema for Website Team Onboarding 
- first_name
- last_name
- email
- github_handle
- first_attended
- last_modified
- last_modified_by
- website_all_team_meeting
- website_dev_meeting
- website_dev_office_hrs

**Comment by aishwaryaharikumar** [comment]
Tables Schema for Weekly Dev Meetings
- meeting_name
- notes
- ~cop_name~
- ~google_drive_id~
- ~repo_team~
- calendar_id
- calendar_invite
- Last updated
- updated_by
- ~project_leads~
- ~project_description~
- ~project_slack~
- ~is_cop~
- ~program_area~
- ~project_supervisory_level~
- ~sdg~

**Comment by ExperimentsInHonesty** [comment]
I am assuming the Weekly Dev Meetings table schema fields are coming from people depo possibly?  Otherwise why would it have sdg and program area... I don't think that those fields are necessary for the meetings.

**Comment by ExperimentsInHonesty** [comment]
At the team meeting 2023-07-07 we decided to remove any fields that are listed in strike through above.

**Comment by hang-justin** [comment]
Tables cleaned up and documentation added

[website-onboarding-form.md](https://github.com/hackforla/tables/blob/main/dev-docs/website-onboarding-form.md)
