### ISSUE TITLE
Audit all drives across all of HfLA to see which ones need their users downgraded 

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tables#51]
### Overview
We need to audit all drives so that we can determine which ones still need to downgrade everyone except pm and org accounts  to contributor status so that we can keep files from being deleted.

### Action Items for Tables team
- [x] write a script to pull the email addresses and permission level of each member of the drive
- [x] do a pr to the repo to store the script.
- [x] Have the script create a csv 
   - [project initials]: google drive permissions
- [x] upload csv to folder
- [x] document script in docs folder on repo

### Post script development actions for product managers
- [ ] Check your list to see if everyone (except PMs and org accounts) have been downgraded to contributor

### Resources/Instructions
- Folder : [Issue 51](https://drive.google.com/drive/folders/1Bh-uW1fospiHrsN8iTdkH3tgX3cuHNJX?usp=share_link)

### Drives
- [x] #59
- [x] https://drive.google.com/open?id=0AFXxG16I9WmnUk9PVA&usp=drive_copy
- [x] https://drive.google.com/open?id=0AK9EyXeY81U5Uk9PVA&usp=drive_copy
- [x] https://drive.google.com/open?id=0AK-gcCeDY7GYUk9PVA&usp=drive_copy
- [x] https://drive.google.com/open?id=0AERAx-iD1idwUk9PVA&usp=drive_copy
- [x] https://drive.google.com/open?id=0AJYSE30n7aJaUk9PVA&usp=drive_copy
- [x] https://drive.google.com/open?id=0AHm1jtnPQgtkUk9PVA&usp=drive_copy
- [x] https://drive.google.com/open?id=0AJHhImYovXJBUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AMdnUkSXicNCUk9PVA&usp=drive_copy
- [x] https://drive.google.com/open?id=0AM1Y2SIfO4nMUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ABybAQUv53kiUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AKq7wKOWdsbWUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ANai8Kc3wh0tUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AAX-8be-yD5JUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AJG5FVtbX9vYUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AOH8_3B5nc_-Uk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ALZlGXAx55mQUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0APAX9L5CskEsUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0APj3SyK5jt0tUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ABhiE6o89TDjUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ADf8U9I8zDMtUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AOyia66xiVyGUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AKWbU6_2dvZuUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AGzI0_b353MxUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AK5Md2_3LvEDUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ACLGQ8FFW2MCUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AOCRQk8utMIyUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ACgRrPVkhnrvUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AAwvkYVbtLbgUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ADbZMfsiwQqRUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AOej-7OgStIPUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AIu3X_nGN_VvUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AGAUfr5IS2YZUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AOFKS-oLsSXyUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AFObCPMUnDWmUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ACKJR3616becUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AKL1C9H1wDPgUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0APJFu_GrzzH7Uk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ADDj1EJQnl75Uk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AMVDRCjyzDgtUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AISloPaWXy2RUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AKJZyM-aER9jUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AKQNmfAwcrImUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ADMIgW43ATU0Uk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AMHGjmh4EJW2Uk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ADKKLIU3-X0GUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ALAVSnCoNBWnUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AInVdW5rllKEUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AO5HWG9daZAtUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ALja8o12Hd1QUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ACjCHzHKLLQxUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AK10edhzz5zKUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0AL_Yo4z3LkyVUk9PVA&usp=drive_copy
- [ ] https://drive.google.com/open?id=0ALKXaRknD6rfUk9PVA&usp=drive_copy
- [x] https://drive.google.com/open?id=0AEsnLxxXzxhVUk9PVA&usp=drive_copy
- [x] https://drive.google.com/open?id=0AGiamFq2AD9FUk9PVA&usp=drive_copy
- [x] https://drive.google.com/open?id=0AEM-JvLinZyTUk9PVA&usp=drive_copy

#### Drive Audit
- [Google Drives permission for tables audit](https://docs.google.com/spreadsheets/d/1ybTRUoizMmwY8RYRG6cu9flkhN4rYCo5dM_iYYdBeWo)
![image](https://github.com/hackforla/tables/assets/37763229/29d197de-b733-4a35-a3db-e354c65633e5)

**Comment by ExperimentsInHonesty** [comment]
We need to audit all the drives to know which  tables@ has permission for and which it does not.

**Comment by wesley115** [comment]
-App Script has different naming convention for permission types, fixed by remapping the name to google drive's permission type
-script generate rows of ["Drive ID"," eamil "," permission "] for every drive tables@hackforla.org has permission in "google_drive_permissions_audit.csv"
-script also generate a list of drives id that tables@hackforla.org doesn't have permission in "driveWithoutPermission"



Currently there are 3 drives on the list above table@ does not have permission 
0AMdnUkSXicNCUk9PVA
0ABhiE6o89TDjUk9PVA
0AEM-JvLinZyTUk9PVA

**Comment by wesley115** [comment]
write draft for doc in the issue

**Comment by wesley115** [comment]
Use 1Password to log into tables@hackforla.org
the script is located in the Scripts > [Google Drive Permissions](https://drive.google.com/drive/folders/1eObjWkjANDQSoJDfcyn7vwPIZlWw-hpK) folder >  Google drives permission audit script

to run, simply run the test function which will call getPermissionsList by passing intended driveID and sheet URL for audit result. 

Since the Drive.Permissions API has different naming convention from what the end users see when they go to a shared drive under drive.google.com, the script remaps the permission list as below:
"organizer"->"manager"
"fileOrganizer"-> "content manager")
"writer"-> "contributor"
"reader" with ''additionalRoles: 'commenter'''-> "commenter"
"reader" only->"viewer");
the script also log driveID that does not have permission to open in another csv file "driveWithoutPermission"

**Comment by bonniewolfe** [comment]
Next step will be creating a markdown file for the repo

**Comment by ExperimentsInHonesty** [comment]
@wesley115 Please provide update 
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by wesley115** [comment]
include created date to file name

**Comment by ExperimentsInHonesty** [comment]
@Rabia2219  and @ExperimentsInHonesty will review this to up or downgrade contribution managers [google_drive_permissions_audit.csv](https://docs.google.com/spreadsheets/d/18iKFxyLylz3fCM3ox4KgBKSLQ8Ix9vrX-iWbC7bUKHw/edit?gid=728703555#gid=728703555&fvid=1797059785)

- [ ] review all the places that [Rabia has access permissions that are not manager](https://docs.google.com/spreadsheets/d/18iKFxyLylz3fCM3ox4KgBKSLQ8Ix9vrX-iWbC7bUKHw/edit?gid=728703555#gid=728703555&fvid=147745861)
   - [x] add the name of the drive
   - [ ] decide what to do (probably upgrade)
   - [ ] update
- [ ] review the drives that a project emails have access to and decide what to do
