### ISSUE TITLE
Add all new volunteers to new google drive (knowlegebase-content)

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tables#55]
### Overview
We need to add all new volunteers to the new drive, knowledgebase-content, as Contributors, so that they can CRU (not D) guides

### Action Items
- [x] add 
- [x] test

### Resources/Instructions
- New Google Drive: https://drive.google.com/drive/folders/0ANa2FF5vnf3xUk9PVA
- Note: no need to do anything with GitHub.  New volunteers get access to the corresponding GitHub repo, through their community of practice GitHub teams. https://github.com/hackforla/knowledgebase-content

**Comment by kennytram** [comment]
To optimize the time for a new volunteer to be added to Knowledge-based content, I basically added another addToDrive line directly inside the onboarding automation script. Otherwise, we would have to wait up to 5 minutes for them to be added to the drive.
