### ISSUE TITLE
Add backend validation for "passphrase" field

### ISSUE THREAD

**Issue by Reltre** [hackforla/tables#73]
### Overview
Add in a backend validation for "passphrase" field to AppScript

### Action Items

- [ ] Research necessary API calls to add in a backend validation
    * It may not be possible to re-render and then give back an error message for a specific user (research this). If not, then try to add a backend validation with a new AppScript that uses an "open" trigger instead of a submit trigger. 
- [ ] Research necessary API calls to re-render form with a sensible error message.
- [ ] Implement backend validation, re-render, and error handling for passphrase field
    * Make sure to check that the validation isn't directly embedded in the HTML elements using "Inspect" tool in your browser.

### Resources/Instructions

* [Google Sheet Event Objects](https://developers.google.com/apps-script/guides/triggers/events#google_sheets_events)
* [FormApp API docs for editing an existing form](https://developers.google.com/apps-script/reference/forms/form-app)
* [Current App Script used for submission hooks](https://script.google.com/u/2/home/projects/1q005a-hE8YA1wOdRUIHSWawFVhSHkSm0a1MJ6CHeYBecSuSnMXeU8yhX/edit)
* [Current Sheet](https://docs.google.com/spreadsheets/d/17vQpPrgdcakl-qVHDhKvChRheJyZMmFhyNDTaoPfeuY/edit?resourcekey#gid=1464356980)

**Comment by Reltre** [comment]
cc: @bonniewolfe

**Comment by hkatzdev** [comment]
Passphrase is the code of conduct secret word, right?
If so, I think it being embedded in the front end is fine (for quick error checking). It seems to change rarely, and the way https://github.com/hackforla/codeofconduct is set up means that you can figure it out by looking at the diff from the original (https://github.com/codeforamerica/codeofconduct/compare/master...hackforla:codeofconduct:master). If a user is using inspect element to bypass reading the Code of Conduct, then they are probably willing to glance at a diff to say a minute of reading.

**Comment by Reltre** [comment]
@hkatzdev This is a fair point. Someone who is willing to go out of their way to look into the code of conduct in codeforamerica would find it via a diff, though I guess Hack For LA isn't directly linked to Code for America now, so they may not make the connection?
@bonniewolfe What are you thoughts? Would you still like to see this as a backend validation? Or move it to the frontend (as it was before)?

**Comment by Reltre** [comment]
I plan to at least explore this possibility over the next day or so. I would like to see at least if the validation that we can create programmatically is technically more robust or different than the one made via the Google Form we have on the FE.
I thin from there we can decide whether this is even worth pursuing.

**Comment by Reltre** [comment]
I've looked into this a bit more, and I think the initial thought that this was feasible was incorrect. I missed some key information that states the validations and Form updates only apply to Edit Mode.
We want this validation to apply while someone is responding. So, it doesn't seem like it's possible with just App Scripts and Google Forms to add in a backend validation for responders to a Form. See `*` note on this [page](https://developers.google.com/apps-script/guides/triggers/events#Google%20Forms-events) for reasoning on why this isn't feasible given the API available to us from Google.

My recommendation is to risk putting it as a text validation on the FE. If we're really not ok with that, we can always just leave the validation empty and continue to manually verify this.

**Comment by Reltre** [comment]
Closing for now since this doesn't seem feasible given the API limitations from Google Workspace
